# Generated by Django 5.2.1 on 2025-05-14 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('climate', models.CharField(max_length=100)),
                ('magic_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Keeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(blank=True, max_length=100, null=True)),
                ('hire_date', models.DateField()),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('date_arrived', models.DateTimeField()),
                ('temperament', models.CharField(blank=True, max_length=100, null=True)),
                ('is_nocturnal', models.BooleanField(default=False)),
                ('habitat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.habitat')),
                ('primary_keeper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.keeper')),
            ],
        ),
        migrations.CreateModel(
            name='CreatureAbilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.IntegerField(blank=True, null=True)),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.creature')),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.specialability')),
            ],
        ),
        migrations.AddField(
            model_name='creature',
            name='abilities',
            field=models.ManyToManyField(through='myapp.CreatureAbilities', to='myapp.specialability'),
        ),
    ]
